import os
import csv
import json
import uuid
from typing import List, Dict, Any, Tuple
from datetime import datetime, timedelta

def get_shadowweb_data() -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, Any]]:
    """Operation ShadowWeb: Cross-Border Narcotics & Hawala Money Laundering Syndicate"""
    nodes = [
        {
            "id": "node_vicky",
            "name": "Vikramaditya Singhania",
            "label": "V. Singhania",
            "type": "person",
            "aliases": ["The Architect", "Vicky Dubai", "Kestrel-9", "V.S. Global"],
            "risk_score": 98,
            "risk_level": "CRITICAL",
            "role": "Syndicate Kingpin",
            "jurisdiction": "Interpol Red Notice / NCB / ED",
            "cctns_fir": "FIR-2024-MH-NCB-0982",
            "fiu_str_id": "STR-2024-FIU-90118",
            "phone": "+971-50-982-1402",
            "bank_account": "EMIRATES_NBD_99210",
            "crypto_address": "0x71CB99210A8374829F8182938192837192837482",
            "location": "Dubai, UAE / Mumbai Overseas",
            "last_active": "2024-10-14 22:45:00",
            "photo_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Primary target. Directs international narcotics shipments and orchestrates Hawala cash drops via Dubai-Mumbai corridor.",
            "metadata": {"passport": "P7829102-IND", "imei_list": ["865420049281726", "865420049281729"]}
        },
        {
            "id": "node_tariq",
            "name": "Tariq Merchant",
            "label": "Tariq 'Bhai' Merchant",
            "type": "person",
            "aliases": ["Uncle T", "Al-Noor Bullion", "T.M. Zaveri"],
            "risk_score": 94,
            "risk_level": "CRITICAL",
            "role": "Chief Hawala Banker",
            "jurisdiction": "ED Mumbai / FIU-IND",
            "cctns_fir": "FIR-2024-MH-CRIME-0412",
            "fiu_str_id": "STR-2024-FIU-84729",
            "phone": "+91-98201-77291",
            "bank_account": "HDFC_ZAVERI_482910",
            "crypto_address": "0x44B829182390192839182938192837192837481B",
            "location": "Zaveri Bazaar, Mumbai",
            "last_active": "2024-10-15 11:20:00",
            "photo_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Handles layered Hawala tokens (currency serial matching). Funnels dirty cash into gold bullion and overseas shell accounts.",
            "metadata": {"pan": "AAECM8291Q", "gstin": "27AAECM8291Q1Z4"}
        },
        {
            "id": "node_apex_logistics",
            "name": "Apex Horizon Global Logistics FZE",
            "label": "Apex Horizon Logistics",
            "type": "shell_company",
            "aliases": ["Apex Shipping FZE", "Horizon Freight Mumbai"],
            "risk_score": 89,
            "risk_level": "HIGH",
            "role": "Front / Shell Entity",
            "jurisdiction": "MCA / Customs Air Cargo",
            "cctns_fir": "FIR-2024-CUSTOMS-081",
            "fiu_str_id": "STR-2024-FIU-99012",
            "phone": "+91-22-6691-0021",
            "bank_account": "STANDARD_CHARTERED_88192",
            "crypto_address": None,
            "location": "Bandra Kurla Complex (BKC), Mumbai",
            "last_active": "2024-10-15 09:30:00",
            "photo_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Invoiced over ₹24.5 Cr in fraudulent maritime freight container services. Used to disguise drug shipments from Bandar Abbas.",
            "metadata": {"cin": "U74999MH2021PTC368291", "directors": ["Rohit Verma", "V. Singhania"]}
        },
        {
            "id": "node_rohit_verma",
            "name": "Rohit Ramesh Verma",
            "label": "Rohit Verma",
            "type": "person",
            "aliases": ["RV Mules", "CryptoKavach", "Rohit V. Director"],
            "risk_score": 87,
            "risk_level": "HIGH",
            "role": "Mule Network Coordinator",
            "jurisdiction": "Cyber Cell Thane / CID",
            "cctns_fir": "FIR-2024-MH-CYBER-112",
            "fiu_str_id": "STR-2024-FIU-77291",
            "phone": "+91-97690-33821",
            "bank_account": "ICICI_BKC_992104",
            "crypto_address": "0x99C718293819283719283748281928371928374C",
            "location": "Navi Mumbai, MH",
            "last_active": "2024-10-15 14:10:00",
            "photo_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Recruits college students and gig workers to open zero-balance current accounts used as cash mules.",
            "metadata": {"aadhaar_masked": "XXXXXXXX4819", "pan": "BRRPV9912K"}
        },
        {
            "id": "node_sameer_courier",
            "name": "Sameer 'Chhotu' Sheikh",
            "label": "Sameer Sheikh",
            "type": "person",
            "aliases": ["Chhotu Courier", "Sammy Rider", "Sameer S."],
            "risk_score": 82,
            "risk_level": "HIGH",
            "role": "Physical Cash / Narcotics Courier",
            "jurisdiction": "Mumbai Police Zone 1",
            "cctns_fir": "FIR-2024-MUM-CRIME-991",
            "fiu_str_id": None,
            "phone": "+91-98192-44102",
            "bank_account": "AXIS_COLABA_119283",
            "crypto_address": None,
            "location": "Bhendi Bazaar / Colaba, Mumbai",
            "last_active": "2024-10-15 18:40:00",
            "photo_url": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Handles dead drops and physical ₹2,000 / ₹500 currency bundles across South Mumbai.",
            "metadata": {"vehicle_number": "MH-01-EA-4912", "imei_list": ["865420049281726"]}
        },
        {
            "id": "node_karan_tech",
            "name": "Karan Malhotra",
            "label": "Karan Malhotra",
            "type": "person",
            "aliases": ["KM-Dev", "CipherGhost", "K. Malhotra"],
            "risk_score": 76,
            "risk_level": "HIGH",
            "role": "Crypto Mixer & SIM Specialist",
            "jurisdiction": "Special Cell Delhi / ED",
            "cctns_fir": "FIR-2024-DL-SPCELL-389",
            "fiu_str_id": "STR-2024-FIU-66291",
            "phone": "+91-99110-88291",
            "bank_account": "KOTAK_CP_448192",
            "crypto_address": "0x33A918239019283918293819283719283748293A",
            "location": "Connaught Place, New Delhi",
            "last_active": "2024-10-15 16:15:00",
            "photo_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
            "is_flagged": False,
            "notes": "Converts Indian Rupee cash receipts into USDT on P2P exchanges and routes through Tornado Cash / Wasabi mixer.",
            "metadata": {"github": "km-dev-ops", "telegram_id": "@km_cipher"}
        },
        {
            "id": "node_mule_account_1",
            "name": "Mule Account #1 (HDFC - Suresh Patel)",
            "label": "HDFC Mule Acct #4829",
            "type": "bank_account",
            "aliases": ["Acct-4829-Suresh", "Layering Acct 1"],
            "risk_score": 72,
            "risk_level": "MEDIUM",
            "role": "Mule Bank Account",
            "jurisdiction": "FIU-IND Alert",
            "cctns_fir": None,
            "fiu_str_id": "STR-2024-FIU-48291",
            "phone": "+91-98765-11223",
            "bank_account": "HDFC0000240-501004829102",
            "crypto_address": None,
            "location": "Ahmedabad, Gujarat",
            "last_active": "2024-10-14 19:10:00",
            "photo_url": None,
            "is_flagged": True,
            "notes": "High velocity in-and-out account. ₹3.4 Crore credited and emptied via ATM & IMPS within 48 hours.",
            "metadata": {"beneficiary_kyc": "Suresh Kantilal Patel", "daily_velocity_inr": 4500000}
        },
        {
            "id": "node_mule_account_2",
            "name": "Mule Account #2 (Axis - Rakesh Mehra)",
            "label": "Axis Mule Acct #1192",
            "type": "bank_account",
            "aliases": ["Acct-1192-Rakesh", "Layering Acct 2"],
            "risk_score": 68,
            "risk_level": "MEDIUM",
            "role": "Mule Bank Account",
            "jurisdiction": "FIU-IND Alert",
            "cctns_fir": None,
            "fiu_str_id": "STR-2024-FIU-11920",
            "phone": "+91-98765-44332",
            "bank_account": "UTIB0000120-918011928340",
            "crypto_address": None,
            "location": "Surat, Gujarat",
            "last_active": "2024-10-14 20:05:00",
            "photo_url": None,
            "is_flagged": False,
            "notes": "Layering mule node used to break single large deposits into micro-transfers to avoid mandatory FIU reporting.",
            "metadata": {"beneficiary_kyc": "Rakesh Mehra", "daily_velocity_inr": 2800000}
        },
        {
            "id": "node_crypto_mixer",
            "name": "Cross-Chain Crypto Mixer Bridge",
            "label": "Mixer Bridge 0x71C...",
            "type": "crypto_wallet",
            "aliases": ["ShadowMix Escrow", "USDT-XMR Bridge"],
            "risk_score": 96,
            "risk_level": "CRITICAL",
            "role": "Laundering Infrastructure",
            "jurisdiction": "International Blockchain Analytics / ED",
            "cctns_fir": None,
            "fiu_str_id": "STR-2024-CRYPTO-9182",
            "phone": None,
            "bank_account": None,
            "crypto_address": "0x71CB99210A8374829F8182938192837192837482",
            "location": "Decentralized (Offshore Routing)",
            "last_active": "2024-10-15 03:22:00",
            "photo_url": None,
            "is_flagged": True,
            "notes": "High risk smart contract pool. 18.2M USDT laundered into Monero privacy coins.",
            "metadata": {"blockchain": "Ethereum / Tron TRC-20", "total_volume_usd": 18200000}
        },
        {
            "id": "node_deepak_telecom",
            "name": "Deepak Mobile Communications",
            "label": "Deepak Telecom Hub",
            "type": "phone",
            "aliases": ["Burner SIM Depot", "Deepak SIMs"],
            "risk_score": 84,
            "risk_level": "HIGH",
            "role": "Burner SIM Supplier",
            "jurisdiction": "DOT / Telecom Vigilance Cell",
            "cctns_fir": "FIR-2024-DEL-TRAI-044",
            "fiu_str_id": None,
            "phone": "+91-11-2384-9102",
            "bank_account": "PNB_CHANDNI_192830",
            "crypto_address": None,
            "location": "Chandni Chowk, Delhi",
            "last_active": "2024-10-14 17:50:00",
            "photo_url": None,
            "is_flagged": True,
            "notes": "Issued over 340 pre-activated SIM cards using forged Aadhaar cards of deceased persons to the syndicate.",
            "metadata": {"forged_sims_detected": 342, "common_tower": "TOWER_DL_CHANDNI_99"}
        },
        {
            "id": "node_ananya_broker",
            "name": "Ananya Sen",
            "label": "Ananya Sen (Broker)",
            "type": "person",
            "aliases": ["A. Sen Real Estate", "Dubai Escrow Agent"],
            "risk_score": 62,
            "risk_level": "MEDIUM",
            "role": "Real Estate Hawala Broker",
            "jurisdiction": "Income Tax Benami Wing",
            "cctns_fir": None,
            "fiu_str_id": "STR-2024-FIU-33910",
            "phone": "+91-98300-11928",
            "bank_account": "KOTAK_KOLKATA_881920",
            "crypto_address": None,
            "location": "Park Street, Kolkata",
            "last_active": "2024-10-13 12:00:00",
            "photo_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
            "is_flagged": False,
            "notes": "Assists Vicky Singhania in purchasing luxury villas in Al Barsha, Dubai using cash adjustments in Kolkata.",
            "metadata": {"properties_linked": 4, "estimated_benami_inr": 185000000}
        },
        {
            "id": "node_inspector_rathore",
            "name": "Sub-Inspector Vijay Rathore (Compromised)",
            "label": "SI Vijay Rathore",
            "type": "person",
            "aliases": ["Zone 1 Contact", "V.R. Alert"],
            "risk_score": 79,
            "risk_level": "HIGH",
            "role": "Corrupt Law Enforcement Insider",
            "jurisdiction": "Anti-Corruption Bureau (ACB)",
            "cctns_fir": "FIR-2024-ACB-MUM-019",
            "fiu_str_id": None,
            "phone": "+91-98210-55912",
            "bank_account": "MAHABANK_MUMBAI_29102",
            "crypto_address": None,
            "location": "Marine Drive, Mumbai",
            "last_active": "2024-10-15 01:12:00",
            "photo_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Tipped off Sameer Sheikh 15 minutes prior to 3 scheduled raid operations. Received ₹45 Lakhs in cash bribes.",
            "metadata": {"police_station": "Colaba PS Zone 1", "badge_no": "MH-POL-8492"}
        }
    ]

    edges = [
        {
            "id": "edge_vicky_tariq",
            "source": "node_vicky",
            "target": "node_tariq",
            "type": "FUND_TRANSFER",
            "label": "Hawala Settlement ₹12.4 Cr",
            "weight": 4.5,
            "amount_inr": 124000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-12 18:30:00",
            "confidence_score": 98,
            "explain_trail": "14 encrypted Hawala chits matched with Dubai export invoices and currency token code serials.",
            "evidence_ids": ["FIU-STR-90118", "CCTNS-MH-0982-EX1"],
            "metadata": {"token_codes": ["7829-DXB-BOM", "9912-GOLD-AU"]}
        },
        {
            "id": "edge_vicky_apex",
            "source": "node_vicky",
            "target": "node_apex_logistics",
            "type": "SHELL_DIRECTOR",
            "label": "Beneficial Owner & Control",
            "weight": 3.8,
            "amount_inr": 85000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-08-01 10:00:00",
            "confidence_score": 95,
            "explain_trail": "Singhania controls 80% shares through nominee shareholder Rohit Verma in Dubai freezone registry.",
            "evidence_ids": ["MCA-DIR-U74999", "DUBAI-FZE-8819"],
            "metadata": {"shareholding_pct": 80.0}
        },
        {
            "id": "edge_apex_rohit",
            "source": "node_apex_logistics",
            "target": "node_rohit_verma",
            "type": "SHELL_DIRECTOR",
            "label": "Nominee Director",
            "weight": 3.2,
            "amount_inr": 24500000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-08-05 14:00:00",
            "confidence_score": 94,
            "explain_trail": "Rohit Verma listed as sole resident Indian director on bank signing mandates.",
            "evidence_ids": ["MCA-DIR-ROHIT-01", "ICICI-SIG-MANDATE"],
            "metadata": {"signing_power": "Full"}
        },
        {
            "id": "edge_rohit_mule1",
            "source": "node_rohit_verma",
            "target": "node_mule_account_1",
            "type": "FUND_TRANSFER",
            "label": "Mule Disbursement ₹3.4 Cr",
            "weight": 3.0,
            "amount_inr": 34000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-10 11:15:00",
            "confidence_score": 92,
            "explain_trail": "Direct IMPS and RTGS batch credits originating from ICICI BKC account to Suresh Patel mule account.",
            "evidence_ids": ["FIU-STR-48291"],
            "metadata": {"batch_id": "IMPS-20241010-0982"}
        },
        {
            "id": "edge_rohit_mule2",
            "source": "node_rohit_verma",
            "target": "node_mule_account_2",
            "type": "FUND_TRANSFER",
            "label": "Layering Transfer ₹2.8 Cr",
            "weight": 2.8,
            "amount_inr": 28000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-11 15:40:00",
            "confidence_score": 90,
            "explain_trail": "Smurfing transactions: 56 micro transfers under ₹50,000 threshold executed within 4 hours.",
            "evidence_ids": ["FIU-STR-11920"],
            "metadata": {"smurf_count": 56}
        },
        {
            "id": "edge_mule1_karan",
            "source": "node_mule_account_1",
            "target": "node_karan_tech",
            "type": "FUND_TRANSFER",
            "label": "P2P Crypto Purchase ₹3.2 Cr",
            "weight": 3.1,
            "amount_inr": 32000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-12 09:20:00",
            "confidence_score": 91,
            "explain_trail": "Purchased 385,000 USDT on Binance P2P desk using Kotak CP account from mule funds.",
            "evidence_ids": ["BINANCE-P2P-ORDER-9812", "KOTAK-TRX-4481"],
            "metadata": {"usdt_amount": 385000}
        },
        {
            "id": "edge_karan_crypto",
            "source": "node_karan_tech",
            "target": "node_crypto_mixer",
            "type": "CRYPTO_TRANSFER",
            "label": "Mixer Deposit 385k USDT",
            "weight": 4.0,
            "amount_inr": 32000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-12 10:45:00",
            "confidence_score": 99,
            "explain_trail": "On-chain transaction hash 0xfa39... confirms deposit into privacy mixer smart contract.",
            "evidence_ids": ["ETHERSCAN-TX-0xfa398201a9"],
            "metadata": {"tx_hash": "0xfa398201a983b819283719283748293819283748"}
        },
        {
            "id": "edge_crypto_vicky",
            "source": "node_crypto_mixer",
            "target": "node_vicky",
            "type": "CRYPTO_TRANSFER",
            "label": "Clean Monero/USDT Exit",
            "weight": 4.2,
            "amount_inr": 30500000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-13 04:10:00",
            "confidence_score": 93,
            "explain_trail": "Mixer exit pool routed equivalent clean assets to Vicky Singhania cold wallet.",
            "evidence_ids": ["TRONSCAN-TX-0x881920"],
            "metadata": {"cleansed_pct": 95.3}
        },
        {
            "id": "edge_tariq_sameer",
            "source": "node_tariq",
            "target": "node_sameer_courier",
            "type": "CALL",
            "label": "48 Encrypted Voice Calls",
            "weight": 3.6,
            "amount_inr": None,
            "call_duration_sec": 7820,
            "call_count": 48,
            "timestamp": "2024-10-14 21:05:00",
            "confidence_score": 96,
            "explain_trail": "High frequency short-duration calls (avg 1.5 min) timed exactly before physical cash drops.",
            "evidence_ids": ["CDR-TEL-98201-98192", "TOWER-BOM-ZAVERI"],
            "metadata": {"tower_location": "Zaveri Bazaar Cell #104"}
        },
        {
            "id": "edge_sameer_vicky_phone",
            "source": "node_sameer_courier",
            "target": "node_vicky",
            "type": "CALL",
            "label": "22 Signal/VoIP Calls",
            "weight": 2.9,
            "amount_inr": None,
            "call_duration_sec": 3120,
            "call_count": 22,
            "timestamp": "2024-10-14 23:12:00",
            "confidence_score": 88,
            "explain_trail": "Direct international encrypted communication matching shared IMEI 865420049281726.",
            "evidence_ids": ["CDR-INTL-971-98192"],
            "metadata": {"imei_match": True}
        },
        {
            "id": "edge_deepak_sameer",
            "source": "node_deepak_telecom",
            "target": "node_sameer_courier",
            "type": "SHARED_ADDRESS",
            "label": "Burner SIM Supply (14 SIMs)",
            "weight": 2.4,
            "amount_inr": None,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-09-18 16:30:00",
            "confidence_score": 87,
            "explain_trail": "14 SIM cards seized from Sameer Sheikh traced directly to batch issued by Deepak Telecoms.",
            "evidence_ids": ["TRAI-SEIZURE-MEMO-44"],
            "metadata": {"sim_batch_id": "SIM-BATCH-2024-09"}
        },
        {
            "id": "edge_deepak_karan",
            "source": "node_deepak_telecom",
            "target": "node_karan_tech",
            "type": "CALL",
            "label": "35 VoIP Setup Calls",
            "weight": 2.2,
            "amount_inr": None,
            "call_duration_sec": 4200,
            "call_count": 35,
            "timestamp": "2024-10-08 19:20:00",
            "confidence_score": 85,
            "explain_trail": "Coordinated setup of virtual SIM gateways and SIP trunk routing.",
            "evidence_ids": ["CDR-DEL-112384-99110"],
            "metadata": {"sip_trunk_ip": "185.220.101.5"}
        },
        {
            "id": "edge_vicky_ananya",
            "source": "node_vicky",
            "target": "node_ananya_broker",
            "type": "FUND_TRANSFER",
            "label": "Benami Property Advance ₹18.5 Cr",
            "weight": 3.5,
            "amount_inr": 185000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-01 12:00:00",
            "confidence_score": 93,
            "explain_trail": "Luxury real estate token advance booked in Dubai through offshore escrow agreement.",
            "evidence_ids": ["BENAMI-IT-DOC-33910"],
            "metadata": {"property_unit": "Villa 42, Al Barsha Heights"}
        },
        {
            "id": "edge_rathore_sameer",
            "source": "node_inspector_rathore",
            "target": "node_sameer_courier",
            "type": "CALL",
            "label": "18 Raid Leak Alerts",
            "weight": 3.9,
            "amount_inr": 4500000.0,
            "call_duration_sec": 1950,
            "call_count": 18,
            "timestamp": "2024-10-15 01:15:00",
            "confidence_score": 97,
            "explain_trail": "Direct calls placed from police station landline & private cell minutes before enforcement raids.",
            "evidence_ids": ["ACB-MUM-TAPE-019", "CDR-POL-98210-98192"],
            "metadata": {"leak_detected": True, "bribe_amount_inr": 4500000}
        }
    ]

    meta = {
        "id": "shadowweb",
        "title": "Operation ShadowWeb",
        "codename": "SHADOW-WEB-2024",
        "description": "Transnational narcotics trafficking and multi-layered Hawala money laundering network operating across Dubai, Mumbai, and New Delhi.",
        "investigating_agency": "Narcotics Control Bureau (NCB) / Enforcement Directorate (ED) / Cyber Crime Special Cell",
        "created_date": "2024-10-15",
        "status": "ACTIVE",
        "lead_investigator": "Joint Director A. K. Shrivastava (IPS)",
        "total_suspects": len(nodes),
        "critical_suspects": len([n for n in nodes if n["risk_level"] in ["CRITICAL", "HIGH"]]),
        "total_volume_inr": sum([e.get("amount_inr", 0) for e in edges if e.get("amount_inr")]),
        "total_calls_monitored": sum([e.get("call_count", 0) for e in edges if e.get("call_count")]),
        "blockchain_verified": True,
        "tags": ["Narcotics", "Hawala", "Crypto Laundering", "Corrupt Official", "Interpol Red Notice"]
    }

    return nodes, edges, meta

def get_phantom_mule_data() -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, Any]]:
    """Operation Phantom Mule: Cyber Extortion & Darknet SIM-Swap Syndicate"""
    nodes = [
        {
            "id": "node_arun_cipher",
            "name": "Arun 'Cipher' Nair",
            "label": "Arun Nair",
            "type": "person",
            "aliases": ["Ghost_Zero", "NairOps", "A.K. Nair Cyber"],
            "risk_score": 95,
            "risk_level": "CRITICAL",
            "role": "Syndicate Head",
            "jurisdiction": "CERT-In / Special Cell Delhi Police",
            "cctns_fir": "FIR-2024-DL-CYBER-882",
            "fiu_str_id": "STR-2024-FIU-41920",
            "phone": "+91-98110-99218",
            "bank_account": "AXIS_BANGALORE_99182",
            "crypto_address": "0x11A9928192837192837482918293819283748291",
            "location": "Bengaluru / Noida Cyber Hub",
            "last_active": "2024-10-15 23:10:00",
            "photo_url": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Orchestrates phishing campaigns targeting high-net-worth senior citizens and ransomware extortions.",
            "metadata": {"darknet_handle": "phantom_root"}
        },
        {
            "id": "node_sahil_hex",
            "name": "Sahil 'Hex' Mehta",
            "label": "Sahil Mehta",
            "type": "person",
            "aliases": ["DarkByte", "HexExploit", "S. Mehta Dev"],
            "risk_score": 88,
            "risk_level": "HIGH",
            "role": "Malware & VoIP Spoofer",
            "jurisdiction": "CID Cyber Crime Bengaluru",
            "cctns_fir": "FIR-2024-KA-CYBER-319",
            "fiu_str_id": None,
            "phone": "+91-99450-11829",
            "bank_account": "KOTAK_KORAMANGALA_3391",
            "crypto_address": "0x55B819283719283748291829381928374829182B",
            "location": "Koramangala, Bengaluru",
            "last_active": "2024-10-15 21:30:00",
            "photo_url": "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Builds APK Android screen-mirroring malware distributed via fake electricity bill SMS links.",
            "metadata": {"github": "hex-byte-labs"}
        },
        {
            "id": "node_pooja_sundaram",
            "name": "Pooja Sundaram",
            "label": "Pooja Sundaram",
            "type": "person",
            "aliases": ["P. Sharma", "FinTech Escrow", "Sundaram Cashier"],
            "risk_score": 85,
            "risk_level": "HIGH",
            "role": "Mule Recruiter & P2P Broker",
            "jurisdiction": "Cyber Crime Hyderabad",
            "cctns_fir": "FIR-2024-TG-CYBER-091",
            "fiu_str_id": "STR-2024-FIU-55192",
            "phone": "+91-97000-88192",
            "bank_account": "HDFC_HITECH_772810",
            "crypto_address": "0x88C192837192837482918293819283748291828C",
            "location": "HITEC City, Hyderabad",
            "last_active": "2024-10-15 19:45:00",
            "photo_url": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
            "is_flagged": True,
            "notes": "Directs a network of 45 student mule bank accounts in Telangana and Andhra Pradesh.",
            "metadata": {"telegram": "@pooja_cash_bridge"}
        },
        {
            "id": "node_jamtara_hub",
            "name": "Jamtara Calling Cell #4",
            "label": "Jamtara VoIP Hub",
            "type": "location",
            "aliases": ["Karmatar Call Center", "Tower-JMT-08"],
            "risk_score": 92,
            "risk_level": "CRITICAL",
            "role": "Social Engineering Call Hub",
            "jurisdiction": "Jharkhand Police / Interstate Task Force",
            "cctns_fir": "FIR-2024-JH-CYBER-401",
            "fiu_str_id": None,
            "phone": "+91-654-229-1092",
            "bank_account": None,
            "crypto_address": None,
            "location": "Karmatar, Jamtara, Jharkhand",
            "last_active": "2024-10-15 17:00:00",
            "photo_url": None,
            "is_flagged": True,
            "notes": "Origin point of over 12,000 automated phishing calls daily spoofing bank managers.",
            "metadata": {"sim_clones_active": 180}
        },
        {
            "id": "node_crypto_vault_phantom",
            "name": "Phantom Hot Wallet (TRC-20)",
            "label": "Vault 0x11A...",
            "type": "crypto_wallet",
            "aliases": ["USDT Liquidity Pool", "Tron Phantom Cashout"],
            "risk_score": 91,
            "risk_level": "CRITICAL",
            "role": "Laundering Vault",
            "jurisdiction": "Cyber Crime Special Cell",
            "cctns_fir": None,
            "fiu_str_id": "STR-2024-CRYPTO-5512",
            "phone": None,
            "bank_account": None,
            "crypto_address": "0x11A9928192837192837482918293819283748291",
            "location": "Decentralized",
            "last_active": "2024-10-15 22:00:00",
            "photo_url": None,
            "is_flagged": True,
            "notes": "Aggregates extortion proceeds into USDT-TRC20 before sending to offshore exchangers.",
            "metadata": {"total_usdt": 2450000}
        },
        {
            "id": "node_mule_gang_hyd",
            "name": "Hyderabad Student Mule Cluster (6 Accounts)",
            "label": "Hyd Mule Cluster",
            "type": "bank_account",
            "aliases": ["Cluster-HYD-Mules", "SBI-Canara Layer"],
            "risk_score": 75,
            "risk_level": "HIGH",
            "role": "Mule Accounts Cluster",
            "jurisdiction": "Hyderabad Cyber Crime",
            "cctns_fir": "FIR-2024-TG-CYBER-119",
            "fiu_str_id": "STR-2024-FIU-99120",
            "phone": "+91-91210-44912",
            "bank_account": "SBI_HYD_4918290",
            "crypto_address": None,
            "location": "Dilsukhnagar, Hyderabad",
            "last_active": "2024-10-15 15:20:00",
            "photo_url": None,
            "is_flagged": True,
            "notes": "Instant withdrawal of phishing victims' funds via Micro-ATMs within 3 minutes of victim OTP entry.",
            "metadata": {"accounts_count": 6}
        }
    ]

    edges = [
        {
            "id": "edge_arun_sahil",
            "source": "node_arun_cipher",
            "target": "node_sahil_hex",
            "type": "CALL",
            "label": "120 Encrypted Telegram Calls",
            "weight": 4.0,
            "amount_inr": None,
            "call_duration_sec": 14500,
            "call_count": 120,
            "timestamp": "2024-10-14 22:15:00",
            "confidence_score": 97,
            "explain_trail": "Malware delivery coordination and payload distribution schedule.",
            "evidence_ids": ["TG-CHAT-EXTRACT-091"],
            "metadata": {"payload_version": "v3.4-screen-grab"}
        },
        {
            "id": "edge_sahil_jamtara",
            "source": "node_sahil_hex",
            "target": "node_jamtara_hub",
            "type": "SHARED_ADDRESS",
            "label": "VoIP SIP Gateway Access",
            "weight": 3.8,
            "amount_inr": None,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-10 18:00:00",
            "confidence_score": 93,
            "explain_trail": "Sahil provided backend API access to spoofed caller-ID gateways to Jamtara callers.",
            "evidence_ids": ["SIP-LOG-JMT-08"],
            "metadata": {"spoofed_cid": "1800-425-3800"}
        },
        {
            "id": "edge_jamtara_mules",
            "source": "node_jamtara_hub",
            "target": "node_mule_gang_hyd",
            "type": "FUND_TRANSFER",
            "label": "Victim Phishing Loot ₹6.2 Cr",
            "weight": 4.5,
            "amount_inr": 62000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-13 14:30:00",
            "confidence_score": 99,
            "explain_trail": "Funds stolen from 480 verified victim complaints routed into Hyderabad mule cluster.",
            "evidence_ids": ["NCRP-1930-PORTAL-COMPLAINTS-480"],
            "metadata": {"victim_count": 480}
        },
        {
            "id": "edge_mules_pooja",
            "source": "node_mule_gang_hyd",
            "target": "node_pooja_sundaram",
            "type": "FUND_TRANSFER",
            "label": "Consolidated Loot ₹5.8 Cr",
            "weight": 4.1,
            "amount_inr": 58000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-14 11:00:00",
            "confidence_score": 96,
            "explain_trail": "Cash collected from Micro-ATMs converted into crypto on OTC Telegram desk.",
            "evidence_ids": ["HDFC-STR-772810"],
            "metadata": {"otc_desk": "Hyderabad-OTC-Fast"}
        },
        {
            "id": "edge_pooja_vault",
            "source": "node_pooja_sundaram",
            "target": "node_crypto_vault_phantom",
            "type": "CRYPTO_TRANSFER",
            "label": "Deposit 680k USDT",
            "weight": 4.2,
            "amount_inr": 56000000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-14 16:20:00",
            "confidence_score": 98,
            "explain_trail": "TRC-20 on-chain transfer to primary syndicate vault.",
            "evidence_ids": ["TRONSCAN-TX-PHANTOM-01"],
            "metadata": {"usdt_amount": 680000}
        },
        {
            "id": "edge_vault_arun",
            "source": "node_crypto_vault_phantom",
            "target": "node_arun_cipher",
            "type": "CRYPTO_TRANSFER",
            "label": "Kingpin Share Exit 500k USDT",
            "weight": 4.4,
            "amount_inr": 41500000.0,
            "call_duration_sec": None,
            "call_count": None,
            "timestamp": "2024-10-15 02:00:00",
            "confidence_score": 95,
            "explain_trail": "Settlement transfer to Arun Nair personal hardware wallet.",
            "evidence_ids": ["TRONSCAN-TX-ARUN-EXIT"],
            "metadata": {"usdt_amount": 500000}
        }
    ]

    meta = {
        "id": "phantom_mule",
        "title": "Operation Phantom Mule",
        "codename": "PHANTOM-MULE-2024",
        "description": "Cross-state cyber extortion, banking trojan malware distribution, and automated Micro-ATM mule network.",
        "investigating_agency": "Indian Cyber Crime Coordination Centre (I4C) / CERT-In / Special Cell Delhi",
        "created_date": "2024-10-15",
        "status": "ACTIVE",
        "lead_investigator": "Superintendent of Police Meenakshi Sundaram (IPS)",
        "total_suspects": len(nodes),
        "critical_suspects": len([n for n in nodes if n["risk_level"] in ["CRITICAL", "HIGH"]]),
        "total_volume_inr": sum([e.get("amount_inr", 0) for e in edges if e.get("amount_inr")]),
        "total_calls_monitored": sum([e.get("call_count", 0) for e in edges if e.get("call_count")]),
        "blockchain_verified": True,
        "tags": ["Cyber Crime", "SIM-Swap", "Phishing", "Crypto Vault", "Jamtara Cell"]
    }

    return nodes, edges, meta

def export_mock_csvs(data_dir: str):
    """Generates standard CSV files suspects.csv, transactions.csv, calls.csv for demo and offline inspection."""
    os.makedirs(data_dir, exist_ok=True)
    nodes, edges, _ = get_shadowweb_data()

    # suspects.csv
    with open(os.path.join(data_dir, "suspects.csv"), "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "name", "aliases", "type", "risk_score", "risk_level", "role", "jurisdiction", "cctns_fir", "phone", "bank_account", "crypto_address", "location"])
        for n in nodes:
            writer.writerow([
                n["id"], n["name"], ";".join(n.get("aliases", [])), n["type"],
                n["risk_score"], n["risk_level"], n["role"], n["jurisdiction"],
                n.get("cctns_fir", ""), n.get("phone", ""), n.get("bank_account", ""),
                n.get("crypto_address", ""), n.get("location", "")
            ])

    # transactions.csv
    with open(os.path.join(data_dir, "transactions.csv"), "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "source", "target", "type", "amount_inr", "timestamp", "confidence_score", "explain_trail"])
        for e in edges:
            if "TRANSFER" in e["type"] or e.get("amount_inr"):
                writer.writerow([
                    e["id"], e["source"], e["target"], e["type"],
                    e.get("amount_inr", 0), e.get("timestamp", ""), e.get("confidence_score", 85),
                    e.get("explain_trail", "")
                ])

    # calls.csv
    with open(os.path.join(data_dir, "calls.csv"), "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "caller", "receiver", "type", "call_count", "call_duration_sec", "timestamp", "confidence_score", "explain_trail"])
        for e in edges:
            if e["type"] == "CALL":
                writer.writerow([
                    e["id"], e["source"], e["target"], e["type"],
                    e.get("call_count", 1), e.get("call_duration_sec", 0), e.get("timestamp", ""),
                    e.get("confidence_score", 85), e.get("explain_trail", "")
                ])
